name: Reusable release and tag workflow
on:
  workflow_call:
    inputs:
      publish_on_pypi:
        description: Upload on pypi public index
        type: boolean
        required: false
        default: false

      publish_on_test_pypi:
        description: Upload on test pypi public index
        type: boolean
        required: false
        default: false

      publish_on_npm:
        description: Upload on npm public index
        type: boolean
        required: false
        default: false

      publish_on_twitter:
        description: Publish changelog on twitter
        type: boolean
        required: false
        default: false
      twitter_message:
        description: Twitter message to append after changelog (i.e. tags)
        type: string
        required: false
        default: #CyberSecurity

      publish_on_ecr:
        description: Publish on ecr
        type: boolean
        required: false
        default: false
      repository:
        description: Repository name
        type: string
        required: false
        default: ${{ github.event.repository.name }}

      dockerfiles:
        description: Path for dockerfiles from working directory
        type: string
        required: false
      working_directory:
        description: Docker build context
        type: string
        required: false
        default: .
      aws_region:
        description: Aws region
        type: string
        required: false
        default: eu-central-1


jobs:
  release_and_tag:
    name: Create release and tag
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    outputs:
      match: ${{ steps.check-tag.outputs.match }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, you do not retrieve the tags

      - name: Check Tag
        id: check-tag
        if: github.base_ref == 'master' || github.base_ref == 'main'
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "match=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Tag and Release
        id: create-release
        if: steps.check-tag.outputs.match == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.pull_request.title }}
          name: Version ${{ github.event.pull_request.title }}
          draft: false
          generate_release_notes: true
          prerelease: false
          target_commitish: ${{ github.base_ref }}
          append_body: true

      - name: Checkout created tag
        uses: actions/checkout@v4
        if: steps.check-tag.outputs.match == 'true' && ( inputs.publish_on_test_pypi || inputs.publish_on_pypi)
        with:
          fetch-depth: 0 # otherwise, you do not retrieve the tags

      - uses: actions/setup-python@v5
        if: steps.check-tag.outputs.match == 'true' && (inputs.publish_on_pypi || inputs.publish_on_test_pypi)
        with:
          python-version: "3.x"

      - name: Install pypa/build
        if: steps.check-tag.outputs.match == 'true' && (inputs.publish_on_pypi || inputs.publish_on_test_pypi)
        run: |
          python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        if: steps.check-tag.outputs.match == 'true' && (inputs.publish_on_pypi || inputs.publish_on_test_pypi)
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Publish to test PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        if: steps.check-tag.outputs.match == 'true' && inputs.publish_on_test_pypi
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        if: steps.check-tag.outputs.match == 'true' && inputs.publish_on_pypi
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - uses: actions/setup-node@v4
        if: steps.check-tag.outputs.match == 'true' && inputs.publish_on_npm
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          scope: '@certego'

      - run: npm publish --access public
        if: steps.check-tag.outputs.match == 'true' && inputs.publish_on_npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_TOKEN }}

      - uses: infraway/tweet-action@v1.0.1
        if: steps.check-tag.outputs.match == 'true' && inputs.publish_on_twitter
        with:
          status: published #IntelOwl ${{github.ref}}! full changelog here: ${GITHUB_SERVER_URL}/${GITHUB_ACTION_REPOSITORY}/blob/${{github.base_ref}}/.github/CHANGELOG.md ${{inputs.twitter_message}}
          api_key: ${{ secrets.TWITTER_API_KEY }}
          api_key_secret: ${{ secrets.TWITTER_API_KEY_SECRET }}
          access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}


  push_on_ecr:
    runs-on: ubuntu-latest
    needs: release_and_tag
    if: github.event.pull_request.merged == true && inputs.publish_on_ecr == true
    strategy:
      matrix:
        dockerfile: ${{ fromJson(inputs.dockerfiles) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, you do not retrieve the tags
      - name: Push on ecr branch
        uses: ./.github/actions/push_on_ecr
        if: github.base_ref == 'master' || github.base_ref == 'main' || github.base_ref == 'develop' || github.base_ref == 'dev'
        with:
          repository: ${{ inputs.repository }}
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          dockerfile: ${{ matrix.dockerfile }}
          image_tag: ${{ ( github.base_ref == 'main' || github.base_ref == 'master' )  && 'prod' || 'stag' }}
          aws_region: ${{ inputs.aws_region }}
          working_directory: ${{ inputs.working_directory }}

      - name: Push on ecr new release
        if: needs.release_and_tag.outputs.match == 'true' && (github.base_ref == 'master' || github.base_ref == 'main' )
        uses: ./.github/actions/push_on_ecr
        with:
          repository: ${{ inputs.repository }}
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          dockerfile: ${{ inputs.dockerfile }}
          image_tag: ${{ github.event.pull_request.title }}
          aws_region: ${{ inputs.aws_region }}
          working_directory: ${{ inputs.working_directory }}